auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: WangLichao.com
url: http://0532.github.io/
feed: /atom.xml
author_info: <a href="http://0532.github.io/">WangLichao</a>
